#
# Mini-Auto-Drive MAD
#
# Copyright (C) 2020 Frank Traenkle
# http://www.modbas.de
#
# MAD User Mission
#
# This file is part of Mini-Auto-Drive.
#
# Mini-Auto-Drive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Mini-Auto-Drive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Mini-Auto-Drive.  If not, see <http://www.gnu.org/licenses/>.
#

uint8 carid
uint32 carLockKey
float32 vmax
uint32 lapCount
uint32 targetParkingSpaceID
bool lockAborted
---
uint8 missionResponse
uint8 MISSIONRESPONSE_GRANTED = 0         # indicates, that the mission has been granted
uint8 MISSIONRESPONSE_ABORTED = 1         # indicates, that the lock has been aborted
uint8 MISSIONRESPONSE_WRONGKEY = 2        # indicates, that the carLockKey was wrong
uint8 MISSIONRESPONSE_OCCUPIED = 3        # indicates, that the selected parking space is occupied
